### ISSUE TITLE
Definition items overflow for long words/phrases

### ISSUE THREAD

**Issue by DaQuirm** [orditori/orditori_client#1]
![IMAGE 2022-03-25 16:37:27](https://user-images.githubusercontent.com/669784/160152872-76717013-8464-4d56-8d72-ef286f7d0ecb.jpg)

Expected: should be wrapped/hyphenated or something like that

**Comment by DaQuirm** [comment]
Closed in 7dc6c94

**Comment by lesnitsky** [comment]
kudos!
